import React from "react";

class Sports extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      value: "Genoa",
      wins: [
        "Benevento",
        "Sassuolo",
        "Inter",
        "Cagliari",
        "Crotone",
        "Verona",
        "Cagliari",
        "Crotone",
        "Verona",
        "Lazio",
        "Chievo",
      ],
    };

    this.handleChange = this.handleChange.bind(this);
    this.handleSubmit = this.handleSubmit.bind(this);
  }

  handleChange(event) {
    this.setState({ value: event.target.value });
  }

  handleSubmit(event) {
    alert("A team was submitted: " + this.state.value);
    event.preventDefault();
    this.wins = this.footie(this.state.value);
    this.setState({ wins: this.wins });
  }

  footie(search) {
    const data = [
      {
        Date: "19/08/17",
        HomeTeam: "Juventus",
        AwayTeam: "Cagliari",
        HomeGoals: 3,
        AwayGoals: 0,
      },
      {
        Date: "19/08/17",
        HomeTeam: "Verona",
        AwayTeam: "Napoli",
        HomeGoals: 1,
        AwayGoals: 3,
      },
      {
        Date: "20/08/17",
        HomeTeam: "Atalanta",
        AwayTeam: "Roma",
        HomeGoals: 0,
        AwayGoals: 1,
      },
      {
        Date: "20/08/17",
        HomeTeam: "Bologna",
        AwayTeam: "Torino",
        HomeGoals: 1,
        AwayGoals: 1,
      },
      {
        Date: "20/08/17",
        HomeTeam: "Crotone",
        AwayTeam: "Milan",
        HomeGoals: 0,
        AwayGoals: 3,
      },
      {
        Date: "20/08/17",
        HomeTeam: "Inter",
        AwayTeam: "Fiorentina",
        HomeGoals: 3,
        AwayGoals: 0,
      },
      {
        Date: "20/08/17",
        HomeTeam: "Lazio",
        AwayTeam: "Spal",
        HomeGoals: 0,
        AwayGoals: 0,
      },
      {
        Date: "20/08/17",
        HomeTeam: "Sampdoria",
        AwayTeam: "Benevento",
        HomeGoals: 2,
        AwayGoals: 1,
      },
      {
        Date: "20/08/17",
        HomeTeam: "Sassuolo",
        AwayTeam: "Genoa",
        HomeGoals: 0,
        AwayGoals: 0,
      },
      {
        Date: "20/08/17",
        HomeTeam: "Udinese",
        AwayTeam: "Chievo",
        HomeGoals: 1,
        AwayGoals: 2,
      },
      {
        Date: "26/08/17",
        HomeTeam: "Benevento",
        AwayTeam: "Bologna",
        HomeGoals: 0,
        AwayGoals: 1,
      },
      {
        Date: "26/08/17",
        HomeTeam: "Genoa",
        AwayTeam: "Juventus",
        HomeGoals: 2,
        AwayGoals: 4,
      },
      {
        Date: "26/08/17",
        HomeTeam: "Roma",
        AwayTeam: "Inter",
        HomeGoals: 1,
        AwayGoals: 3,
      },
      {
        Date: "27/08/17",
        HomeTeam: "Chievo",
        AwayTeam: "Lazio",
        HomeGoals: 1,
        AwayGoals: 2,
      },
      {
        Date: "27/08/17",
        HomeTeam: "Crotone",
        AwayTeam: "Verona",
        HomeGoals: 0,
        AwayGoals: 0,
      },
      {
        Date: "27/08/17",
        HomeTeam: "Fiorentina",
        AwayTeam: "Sampdoria",
        HomeGoals: 1,
        AwayGoals: 2,
      },
      {
        Date: "27/08/17",
        HomeTeam: "Milan",
        AwayTeam: "Cagliari",
        HomeGoals: 2,
        AwayGoals: 1,
      },
      {
        Date: "27/08/17",
        HomeTeam: "Napoli",
        AwayTeam: "Atalanta",
        HomeGoals: 3,
        AwayGoals: 1,
      },
      {
        Date: "27/08/17",
        HomeTeam: "Spal",
        AwayTeam: "Udinese",
        HomeGoals: 3,
        AwayGoals: 2,
      },
      {
        Date: "27/08/17",
        HomeTeam: "Torino",
        AwayTeam: "Sassuolo",
        HomeGoals: 3,
        AwayGoals: 0,
      },
      {
        Date: "09/09/17",
        HomeTeam: "Juventus",
        AwayTeam: "Chievo",
        HomeGoals: 3,
        AwayGoals: 0,
      },
      {
        Date: "10/09/17",
        HomeTeam: "Atalanta",
        AwayTeam: "Sassuolo",
        HomeGoals: 2,
        AwayGoals: 1,
      },
      {
        Date: "10/09/17",
        HomeTeam: "Benevento",
        AwayTeam: "Torino",
        HomeGoals: 0,
        AwayGoals: 1,
      },
      {
        Date: "10/09/17",
        HomeTeam: "Bologna",
        AwayTeam: "Napoli",
        HomeGoals: 0,
        AwayGoals: 3,
      },
      {
        Date: "10/09/17",
        HomeTeam: "Cagliari",
        AwayTeam: "Crotone",
        HomeGoals: 1,
        AwayGoals: 0,
      },
      {
        Date: "10/09/17",
        HomeTeam: "Inter",
        AwayTeam: "Spal",
        HomeGoals: 2,
        AwayGoals: 0,
      },
      {
        Date: "10/09/17",
        HomeTeam: "Lazio",
        AwayTeam: "Milan",
        HomeGoals: 4,
        AwayGoals: 1,
      },
      {
        Date: "10/09/17",
        HomeTeam: "Udinese",
        AwayTeam: "Genoa",
        HomeGoals: 1,
        AwayGoals: 0,
      },
      {
        Date: "10/09/17",
        HomeTeam: "Verona",
        AwayTeam: "Fiorentina",
        HomeGoals: 0,
        AwayGoals: 5,
      },
      {
        Date: "16/09/17",
        HomeTeam: "Crotone",
        AwayTeam: "Inter",
        HomeGoals: 0,
        AwayGoals: 2,
      },
      {
        Date: "16/09/17",
        HomeTeam: "Fiorentina",
        AwayTeam: "Bologna",
        HomeGoals: 2,
        AwayGoals: 1,
      },
      {
        Date: "16/09/17",
        HomeTeam: "Roma",
        AwayTeam: "Verona",
        HomeGoals: 3,
        AwayGoals: 0,
      },
      {
        Date: "17/09/17",
        HomeTeam: "Chievo",
        AwayTeam: "Atalanta",
        HomeGoals: 1,
        AwayGoals: 1,
      },
      {
        Date: "17/09/17",
        HomeTeam: "Genoa",
        AwayTeam: "Lazio",
        HomeGoals: 2,
        AwayGoals: 3,
      },
      {
        Date: "17/09/17",
        HomeTeam: "Milan",
        AwayTeam: "Udinese",
        HomeGoals: 2,
        AwayGoals: 1,
      },
      {
        Date: "17/09/17",
        HomeTeam: "Napoli",
        AwayTeam: "Benevento",
        HomeGoals: 6,
        AwayGoals: 0,
      },
      {
        Date: "17/09/17",
        HomeTeam: "Sassuolo",
        AwayTeam: "Juventus",
        HomeGoals: 1,
        AwayGoals: 3,
      },
      {
        Date: "17/09/17",
        HomeTeam: "Spal",
        AwayTeam: "Cagliari",
        HomeGoals: 0,
        AwayGoals: 2,
      },
      {
        Date: "17/09/17",
        HomeTeam: "Torino",
        AwayTeam: "Sampdoria",
        HomeGoals: 2,
        AwayGoals: 2,
      },
      {
        Date: "19/09/17",
        HomeTeam: "Bologna",
        AwayTeam: "Inter",
        HomeGoals: 1,
        AwayGoals: 1,
      },
      {
        Date: "20/09/17",
        HomeTeam: "Atalanta",
        AwayTeam: "Crotone",
        HomeGoals: 5,
        AwayGoals: 1,
      },
      {
        Date: "20/09/17",
        HomeTeam: "Benevento",
        AwayTeam: "Roma",
        HomeGoals: 0,
        AwayGoals: 4,
      },
      {
        Date: "20/09/17",
        HomeTeam: "Cagliari",
        AwayTeam: "Sassuolo",
        HomeGoals: 0,
        AwayGoals: 1,
      },
      {
        Date: "20/09/17",
        HomeTeam: "Genoa",
        AwayTeam: "Chievo",
        HomeGoals: 1,
        AwayGoals: 1,
      },
      {
        Date: "20/09/17",
        HomeTeam: "Juventus",
        AwayTeam: "Fiorentina",
        HomeGoals: 1,
        AwayGoals: 0,
      },
      {
        Date: "20/09/17",
        HomeTeam: "Lazio",
        AwayTeam: "Napoli",
        HomeGoals: 1,
        AwayGoals: 4,
      },
      {
        Date: "20/09/17",
        HomeTeam: "Milan",
        AwayTeam: "Spal",
        HomeGoals: 2,
        AwayGoals: 0,
      },
      {
        Date: "20/09/17",
        HomeTeam: "Udinese",
        AwayTeam: "Torino",
        HomeGoals: 2,
        AwayGoals: 3,
      },
      {
        Date: "20/09/17",
        HomeTeam: "Verona",
        AwayTeam: "Sampdoria",
        HomeGoals: 0,
        AwayGoals: 0,
      },
      {
        Date: "23/09/17",
        HomeTeam: "Juventus",
        AwayTeam: "Torino",
        HomeGoals: 4,
        AwayGoals: 0,
      },
      {
        Date: "23/09/17",
        HomeTeam: "Roma",
        AwayTeam: "Udinese",
        HomeGoals: 3,
        AwayGoals: 1,
      },
      {
        Date: "23/09/17",
        HomeTeam: "Spal",
        AwayTeam: "Napoli",
        HomeGoals: 2,
        AwayGoals: 3,
      },
      {
        Date: "24/09/17",
        HomeTeam: "Cagliari",
        AwayTeam: "Chievo",
        HomeGoals: 0,
        AwayGoals: 2,
      },
      {
        Date: "24/09/17",
        HomeTeam: "Crotone",
        AwayTeam: "Benevento",
        HomeGoals: 2,
        AwayGoals: 0,
      },
      {
        Date: "24/09/17",
        HomeTeam: "Fiorentina",
        AwayTeam: "Atalanta",
        HomeGoals: 1,
        AwayGoals: 1,
      },
      {
        Date: "24/09/17",
        HomeTeam: "Inter",
        AwayTeam: "Genoa",
        HomeGoals: 1,
        AwayGoals: 0,
      },
      {
        Date: "24/09/17",
        HomeTeam: "Sampdoria",
        AwayTeam: "Milan",
        HomeGoals: 2,
        AwayGoals: 0,
      },
      {
        Date: "24/09/17",
        HomeTeam: "Sassuolo",
        AwayTeam: "Bologna",
        HomeGoals: 0,
        AwayGoals: 1,
      },
      {
        Date: "24/09/17",
        HomeTeam: "Verona",
        AwayTeam: "Lazio",
        HomeGoals: 0,
        AwayGoals: 3,
      },
      {
        Date: "30/09/17",
        HomeTeam: "Genoa",
        AwayTeam: "Bologna",
        HomeGoals: 0,
        AwayGoals: 1,
      },
      {
        Date: "30/09/17",
        HomeTeam: "Udinese",
        AwayTeam: "Sampdoria",
        HomeGoals: 4,
        AwayGoals: 0,
      },
      {
        Date: "01/10/17",
        HomeTeam: "Atalanta",
        AwayTeam: "Juventus",
        HomeGoals: 2,
        AwayGoals: 2,
      },
      {
        Date: "01/10/17",
        HomeTeam: "Benevento",
        AwayTeam: "Inter",
        HomeGoals: 1,
        AwayGoals: 2,
      },
      {
        Date: "01/10/17",
        HomeTeam: "Chievo",
        AwayTeam: "Fiorentina",
        HomeGoals: 2,
        AwayGoals: 1,
      },
      {
        Date: "01/10/17",
        HomeTeam: "Lazio",
        AwayTeam: "Sassuolo",
        HomeGoals: 6,
        AwayGoals: 1,
      },
      {
        Date: "01/10/17",
        HomeTeam: "Milan",
        AwayTeam: "Roma",
        HomeGoals: 0,
        AwayGoals: 2,
      },
      {
        Date: "01/10/17",
        HomeTeam: "Napoli",
        AwayTeam: "Cagliari",
        HomeGoals: 3,
        AwayGoals: 0,
      },
      {
        Date: "01/10/17",
        HomeTeam: "Spal",
        AwayTeam: "Crotone",
        HomeGoals: 1,
        AwayGoals: 1,
      },
      {
        Date: "01/10/17",
        HomeTeam: "Torino",
        AwayTeam: "Verona",
        HomeGoals: 2,
        AwayGoals: 2,
      },
      {
        Date: "14/10/17",
        HomeTeam: "Juventus",
        AwayTeam: "Lazio",
        HomeGoals: 1,
        AwayGoals: 2,
      },
      {
        Date: "14/10/17",
        HomeTeam: "Roma",
        AwayTeam: "Napoli",
        HomeGoals: 0,
        AwayGoals: 1,
      },
      {
        Date: "15/10/17",
        HomeTeam: "Bologna",
        AwayTeam: "Spal",
        HomeGoals: 2,
        AwayGoals: 1,
      },
      {
        Date: "15/10/17",
        HomeTeam: "Cagliari",
        AwayTeam: "Genoa",
        HomeGoals: 2,
        AwayGoals: 3,
      },
      {
        Date: "15/10/17",
        HomeTeam: "Crotone",
        AwayTeam: "Torino",
        HomeGoals: 2,
        AwayGoals: 2,
      },
      {
        Date: "15/10/17",
        HomeTeam: "Fiorentina",
        AwayTeam: "Udinese",
        HomeGoals: 2,
        AwayGoals: 1,
      },
      {
        Date: "15/10/17",
        HomeTeam: "Inter",
        AwayTeam: "Milan",
        HomeGoals: 3,
        AwayGoals: 2,
      },
      {
        Date: "15/10/17",
        HomeTeam: "Sampdoria",
        AwayTeam: "Atalanta",
        HomeGoals: 3,
        AwayGoals: 1,
      },
      {
        Date: "15/10/17",
        HomeTeam: "Sassuolo",
        AwayTeam: "Chievo",
        HomeGoals: 0,
        AwayGoals: 0,
      },
      {
        Date: "16/10/17",
        HomeTeam: "Verona",
        AwayTeam: "Benevento",
        HomeGoals: 1,
        AwayGoals: 0,
      },
      {
        Date: "21/10/17",
        HomeTeam: "Napoli",
        AwayTeam: "Inter",
        HomeGoals: 0,
        AwayGoals: 0,
      },
      {
        Date: "21/10/17",
        HomeTeam: "Sampdoria",
        AwayTeam: "Crotone",
        HomeGoals: 5,
        AwayGoals: 0,
      },
      {
        Date: "22/10/17",
        HomeTeam: "Atalanta",
        AwayTeam: "Bologna",
        HomeGoals: 1,
        AwayGoals: 0,
      },
      {
        Date: "22/10/17",
        HomeTeam: "Benevento",
        AwayTeam: "Fiorentina",
        HomeGoals: 0,
        AwayGoals: 3,
      },
      {
        Date: "22/10/17",
        HomeTeam: "Chievo",
        AwayTeam: "Verona",
        HomeGoals: 3,
        AwayGoals: 2,
      },
      {
        Date: "22/10/17",
        HomeTeam: "Lazio",
        AwayTeam: "Cagliari",
        HomeGoals: 3,
        AwayGoals: 0,
      },
      {
        Date: "22/10/17",
        HomeTeam: "Milan",
        AwayTeam: "Genoa",
        HomeGoals: 0,
        AwayGoals: 0,
      },
      {
        Date: "22/10/17",
        HomeTeam: "Spal",
        AwayTeam: "Sassuolo",
        HomeGoals: 0,
        AwayGoals: 1,
      },
      {
        Date: "22/10/17",
        HomeTeam: "Torino",
        AwayTeam: "Roma",
        HomeGoals: 0,
        AwayGoals: 1,
      },
      {
        Date: "22/10/17",
        HomeTeam: "Udinese",
        AwayTeam: "Juventus",
        HomeGoals: 2,
        AwayGoals: 6,
      },
      {
        Date: "24/10/17",
        HomeTeam: "Inter",
        AwayTeam: "Sampdoria",
        HomeGoals: 3,
        AwayGoals: 2,
      },
      {
        Date: "25/10/17",
        HomeTeam: "Atalanta",
        AwayTeam: "Verona",
        HomeGoals: 3,
        AwayGoals: 0,
      },
      {
        Date: "25/10/17",
        HomeTeam: "Bologna",
        AwayTeam: "Lazio",
        HomeGoals: 1,
        AwayGoals: 2,
      },
      {
        Date: "25/10/17",
        HomeTeam: "Cagliari",
        AwayTeam: "Benevento",
        HomeGoals: 2,
        AwayGoals: 1,
      },
      {
        Date: "25/10/17",
        HomeTeam: "Chievo",
        AwayTeam: "Milan",
        HomeGoals: 1,
        AwayGoals: 4,
      },
      {
        Date: "25/10/17",
        HomeTeam: "Fiorentina",
        AwayTeam: "Torino",
        HomeGoals: 3,
        AwayGoals: 0,
      },
      {
        Date: "25/10/17",
        HomeTeam: "Genoa",
        AwayTeam: "Napoli",
        HomeGoals: 2,
        AwayGoals: 3,
      },
      {
        Date: "25/10/17",
        HomeTeam: "Juventus",
        AwayTeam: "Spal",
        HomeGoals: 4,
        AwayGoals: 1,
      },
      {
        Date: "25/10/17",
        HomeTeam: "Roma",
        AwayTeam: "Crotone",
        HomeGoals: 1,
        AwayGoals: 0,
      },
      {
        Date: "25/10/17",
        HomeTeam: "Sassuolo",
        AwayTeam: "Udinese",
        HomeGoals: 0,
        AwayGoals: 1,
      },
      {
        Date: "28/10/17",
        HomeTeam: "Milan",
        AwayTeam: "Juventus",
        HomeGoals: 0,
        AwayGoals: 2,
      },
      {
        Date: "28/10/17",
        HomeTeam: "Roma",
        AwayTeam: "Bologna",
        HomeGoals: 1,
        AwayGoals: 0,
      },
      {
        Date: "29/10/17",
        HomeTeam: "Benevento",
        AwayTeam: "Lazio",
        HomeGoals: 1,
        AwayGoals: 5,
      },
      {
        Date: "29/10/17",
        HomeTeam: "Crotone",
        AwayTeam: "Fiorentina",
        HomeGoals: 2,
        AwayGoals: 1,
      },
      {
        Date: "29/10/17",
        HomeTeam: "Napoli",
        AwayTeam: "Sassuolo",
        HomeGoals: 3,
        AwayGoals: 1,
      },
      {
        Date: "29/10/17",
        HomeTeam: "Sampdoria",
        AwayTeam: "Chievo",
        HomeGoals: 4,
        AwayGoals: 1,
      },
      {
        Date: "29/10/17",
        HomeTeam: "Spal",
        AwayTeam: "Genoa",
        HomeGoals: 1,
        AwayGoals: 0,
      },
      {
        Date: "29/10/17",
        HomeTeam: "Torino",
        AwayTeam: "Cagliari",
        HomeGoals: 2,
        AwayGoals: 1,
      },
      {
        Date: "29/10/17",
        HomeTeam: "Udinese",
        AwayTeam: "Atalanta",
        HomeGoals: 2,
        AwayGoals: 1,
      },
      {
        Date: "30/10/17",
        HomeTeam: "Verona",
        AwayTeam: "Inter",
        HomeGoals: 1,
        AwayGoals: 2,
      },
      {
        Date: "04/11/17",
        HomeTeam: "Bologna",
        AwayTeam: "Crotone",
        HomeGoals: 2,
        AwayGoals: 3,
      },
      {
        Date: "04/11/17",
        HomeTeam: "Genoa",
        AwayTeam: "Sampdoria",
        HomeGoals: 0,
        AwayGoals: 2,
      },
      {
        Date: "05/11/17",
        HomeTeam: "Atalanta",
        AwayTeam: "Spal",
        HomeGoals: 1,
        AwayGoals: 1,
      },
      {
        Date: "05/11/17",
        HomeTeam: "Cagliari",
        AwayTeam: "Verona",
        HomeGoals: 2,
        AwayGoals: 1,
      },
      {
        Date: "05/11/17",
        HomeTeam: "Chievo",
        AwayTeam: "Napoli",
        HomeGoals: 0,
        AwayGoals: 0,
      },
      {
        Date: "05/11/17",
        HomeTeam: "Fiorentina",
        AwayTeam: "Roma",
        HomeGoals: 2,
        AwayGoals: 4,
      },
      {
        Date: "05/11/17",
        HomeTeam: "Inter",
        AwayTeam: "Torino",
        HomeGoals: 1,
        AwayGoals: 1,
      },
      {
        Date: "05/11/17",
        HomeTeam: "Juventus",
        AwayTeam: "Benevento",
        HomeGoals: 2,
        AwayGoals: 1,
      },
      {
        Date: "05/11/17",
        HomeTeam: "Sassuolo",
        AwayTeam: "Milan",
        HomeGoals: 0,
        AwayGoals: 2,
      },
      {
        Date: "18/11/17",
        HomeTeam: "Napoli",
        AwayTeam: "Milan",
        HomeGoals: 2,
        AwayGoals: 1,
      },
      {
        Date: "18/11/17",
        HomeTeam: "Roma",
        AwayTeam: "Lazio",
        HomeGoals: 2,
        AwayGoals: 1,
      },
      {
        Date: "19/11/17",
        HomeTeam: "Benevento",
        AwayTeam: "Sassuolo",
        HomeGoals: 1,
        AwayGoals: 2,
      },
      {
        Date: "19/11/17",
        HomeTeam: "Crotone",
        AwayTeam: "Genoa",
        HomeGoals: 0,
        AwayGoals: 1,
      },
      {
        Date: "19/11/17",
        HomeTeam: "Inter",
        AwayTeam: "Atalanta",
        HomeGoals: 2,
        AwayGoals: 0,
      },
      {
        Date: "19/11/17",
        HomeTeam: "Sampdoria",
        AwayTeam: "Juventus",
        HomeGoals: 3,
        AwayGoals: 2,
      },
      {
        Date: "19/11/17",
        HomeTeam: "Spal",
        AwayTeam: "Fiorentina",
        HomeGoals: 1,
        AwayGoals: 1,
      },
      {
        Date: "19/11/17",
        HomeTeam: "Torino",
        AwayTeam: "Chievo",
        HomeGoals: 1,
        AwayGoals: 1,
      },
      {
        Date: "19/11/17",
        HomeTeam: "Udinese",
        AwayTeam: "Cagliari",
        HomeGoals: 0,
        AwayGoals: 1,
      },
      {
        Date: "20/11/17",
        HomeTeam: "Verona",
        AwayTeam: "Bologna",
        HomeGoals: 2,
        AwayGoals: 3,
      },
      {
        Date: "25/11/17",
        HomeTeam: "Bologna",
        AwayTeam: "Sampdoria",
        HomeGoals: 3,
        AwayGoals: 0,
      },
      {
        Date: "25/11/17",
        HomeTeam: "Cagliari",
        AwayTeam: "Inter",
        HomeGoals: 1,
        AwayGoals: 3,
      },
      {
        Date: "25/11/17",
        HomeTeam: "Chievo",
        AwayTeam: "Spal",
        HomeGoals: 2,
        AwayGoals: 1,
      },
      {
        Date: "25/11/17",
        HomeTeam: "Sassuolo",
        AwayTeam: "Verona",
        HomeGoals: 0,
        AwayGoals: 2,
      },
      {
        Date: "26/11/17",
        HomeTeam: "Genoa",
        AwayTeam: "Roma",
        HomeGoals: 1,
        AwayGoals: 1,
      },
      {
        Date: "26/11/17",
        HomeTeam: "Juventus",
        AwayTeam: "Crotone",
        HomeGoals: 3,
        AwayGoals: 0,
      },
      {
        Date: "26/11/17",
        HomeTeam: "Lazio",
        AwayTeam: "Fiorentina",
        HomeGoals: 1,
        AwayGoals: 1,
      },
      {
        Date: "26/11/17",
        HomeTeam: "Milan",
        AwayTeam: "Torino",
        HomeGoals: 0,
        AwayGoals: 0,
      },
      {
        Date: "26/11/17",
        HomeTeam: "Udinese",
        AwayTeam: "Napoli",
        HomeGoals: 0,
        AwayGoals: 1,
      },
      {
        Date: "27/11/17",
        HomeTeam: "Atalanta",
        AwayTeam: "Benevento",
        HomeGoals: 1,
        AwayGoals: 0,
      },
      {
        Date: "01/12/17",
        HomeTeam: "Napoli",
        AwayTeam: "Juventus",
        HomeGoals: 0,
        AwayGoals: 1,
      },
      {
        Date: "01/12/17",
        HomeTeam: "Roma",
        AwayTeam: "Spal",
        HomeGoals: 3,
        AwayGoals: 1,
      },
      {
        Date: "02/12/17",
        HomeTeam: "Torino",
        AwayTeam: "Atalanta",
        HomeGoals: 1,
        AwayGoals: 1,
      },
      {
        Date: "03/12/17",
        HomeTeam: "Benevento",
        AwayTeam: "Milan",
        HomeGoals: 2,
        AwayGoals: 2,
      },
      {
        Date: "03/12/17",
        HomeTeam: "Bologna",
        AwayTeam: "Cagliari",
        HomeGoals: 1,
        AwayGoals: 1,
      },
      {
        Date: "03/12/17",
        HomeTeam: "Fiorentina",
        AwayTeam: "Sassuolo",
        HomeGoals: 3,
        AwayGoals: 0,
      },
      {
        Date: "03/12/17",
        HomeTeam: "Inter",
        AwayTeam: "Chievo",
        HomeGoals: 5,
        AwayGoals: 0,
      },
      {
        Date: "03/12/17",
        HomeTeam: "Sampdoria",
        AwayTeam: "Lazio",
        HomeGoals: 1,
        AwayGoals: 2,
      },
      {
        Date: "04/12/17",
        HomeTeam: "Crotone",
        AwayTeam: "Udinese",
        HomeGoals: 0,
        AwayGoals: 3,
      },
      {
        Date: "04/12/17",
        HomeTeam: "Verona",
        AwayTeam: "Genoa",
        HomeGoals: 0,
        AwayGoals: 1,
      },
      {
        Date: "09/12/17",
        HomeTeam: "Cagliari",
        AwayTeam: "Sampdoria",
        HomeGoals: 2,
        AwayGoals: 2,
      },
      {
        Date: "09/12/17",
        HomeTeam: "Juventus",
        AwayTeam: "Inter",
        HomeGoals: 0,
        AwayGoals: 0,
      },
      {
        Date: "10/12/17",
        HomeTeam: "Chievo",
        AwayTeam: "Roma",
        HomeGoals: 0,
        AwayGoals: 0,
      },
      {
        Date: "10/12/17",
        HomeTeam: "Milan",
        AwayTeam: "Bologna",
        HomeGoals: 2,
        AwayGoals: 1,
      },
      {
        Date: "10/12/17",
        HomeTeam: "Napoli",
        AwayTeam: "Fiorentina",
        HomeGoals: 0,
        AwayGoals: 0,
      },
      {
        Date: "10/12/17",
        HomeTeam: "Sassuolo",
        AwayTeam: "Crotone",
        HomeGoals: 2,
        AwayGoals: 1,
      },
      {
        Date: "10/12/17",
        HomeTeam: "Spal",
        AwayTeam: "Verona",
        HomeGoals: 2,
        AwayGoals: 2,
      },
      {
        Date: "10/12/17",
        HomeTeam: "Udinese",
        AwayTeam: "Benevento",
        HomeGoals: 2,
        AwayGoals: 0,
      },
      {
        Date: "11/12/17",
        HomeTeam: "Lazio",
        AwayTeam: "Torino",
        HomeGoals: 1,
        AwayGoals: 3,
      },
      {
        Date: "12/12/17",
        HomeTeam: "Genoa",
        AwayTeam: "Atalanta",
        HomeGoals: 1,
        AwayGoals: 2,
      },
      {
        Date: "16/12/17",
        HomeTeam: "Inter",
        AwayTeam: "Udinese",
        HomeGoals: 1,
        AwayGoals: 3,
      },
      {
        Date: "16/12/17",
        HomeTeam: "Roma",
        AwayTeam: "Cagliari",
        HomeGoals: 1,
        AwayGoals: 0,
      },
      {
        Date: "16/12/17",
        HomeTeam: "Torino",
        AwayTeam: "Napoli",
        HomeGoals: 1,
        AwayGoals: 3,
      },
      {
        Date: "17/12/17",
        HomeTeam: "Atalanta",
        AwayTeam: "Lazio",
        HomeGoals: 3,
        AwayGoals: 3,
      },
      {
        Date: "17/12/17",
        HomeTeam: "Benevento",
        AwayTeam: "Spal",
        HomeGoals: 1,
        AwayGoals: 2,
      },
      {
        Date: "17/12/17",
        HomeTeam: "Bologna",
        AwayTeam: "Juventus",
        HomeGoals: 0,
        AwayGoals: 3,
      },
      {
        Date: "17/12/17",
        HomeTeam: "Crotone",
        AwayTeam: "Chievo",
        HomeGoals: 1,
        AwayGoals: 0,
      },
      {
        Date: "17/12/17",
        HomeTeam: "Fiorentina",
        AwayTeam: "Genoa",
        HomeGoals: 0,
        AwayGoals: 0,
      },
      {
        Date: "17/12/17",
        HomeTeam: "Sampdoria",
        AwayTeam: "Sassuolo",
        HomeGoals: 0,
        AwayGoals: 1,
      },
      {
        Date: "17/12/17",
        HomeTeam: "Verona",
        AwayTeam: "Milan",
        HomeGoals: 3,
        AwayGoals: 0,
      },
      {
        Date: "22/12/17",
        HomeTeam: "Cagliari",
        AwayTeam: "Fiorentina",
        HomeGoals: 0,
        AwayGoals: 1,
      },
      {
        Date: "22/12/17",
        HomeTeam: "Chievo",
        AwayTeam: "Bologna",
        HomeGoals: 2,
        AwayGoals: 3,
      },
      {
        Date: "23/12/17",
        HomeTeam: "Genoa",
        AwayTeam: "Benevento",
        HomeGoals: 1,
        AwayGoals: 0,
      },
      {
        Date: "23/12/17",
        HomeTeam: "Juventus",
        AwayTeam: "Roma",
        HomeGoals: 1,
        AwayGoals: 0,
      },
      {
        Date: "23/12/17",
        HomeTeam: "Lazio",
        AwayTeam: "Crotone",
        HomeGoals: 4,
        AwayGoals: 0,
      },
      {
        Date: "23/12/17",
        HomeTeam: "Milan",
        AwayTeam: "Atalanta",
        HomeGoals: 0,
        AwayGoals: 2,
      },
      {
        Date: "23/12/17",
        HomeTeam: "Napoli",
        AwayTeam: "Sampdoria",
        HomeGoals: 3,
        AwayGoals: 2,
      },
      {
        Date: "23/12/17",
        HomeTeam: "Sassuolo",
        AwayTeam: "Inter",
        HomeGoals: 1,
        AwayGoals: 0,
      },
      {
        Date: "23/12/17",
        HomeTeam: "Spal",
        AwayTeam: "Torino",
        HomeGoals: 2,
        AwayGoals: 2,
      },
      {
        Date: "23/12/17",
        HomeTeam: "Udinese",
        AwayTeam: "Verona",
        HomeGoals: 4,
        AwayGoals: 0,
      },
      {
        Date: "29/12/17",
        HomeTeam: "Crotone",
        AwayTeam: "Napoli",
        HomeGoals: 0,
        AwayGoals: 1,
      },
      {
        Date: "30/12/17",
        HomeTeam: "Atalanta",
        AwayTeam: "Cagliari",
        HomeGoals: 1,
        AwayGoals: 2,
      },
      {
        Date: "30/12/17",
        HomeTeam: "Benevento",
        AwayTeam: "Chievo",
        HomeGoals: 1,
        AwayGoals: 0,
      },
      {
        Date: "30/12/17",
        HomeTeam: "Bologna",
        AwayTeam: "Udinese",
        HomeGoals: 1,
        AwayGoals: 2,
      },
      {
        Date: "30/12/17",
        HomeTeam: "Fiorentina",
        AwayTeam: "Milan",
        HomeGoals: 1,
        AwayGoals: 1,
      },
      {
        Date: "30/12/17",
        HomeTeam: "Inter",
        AwayTeam: "Lazio",
        HomeGoals: 0,
        AwayGoals: 0,
      },
      {
        Date: "30/12/17",
        HomeTeam: "Roma",
        AwayTeam: "Sassuolo",
        HomeGoals: 1,
        AwayGoals: 1,
      },
      {
        Date: "30/12/17",
        HomeTeam: "Sampdoria",
        AwayTeam: "Spal",
        HomeGoals: 2,
        AwayGoals: 0,
      },
      {
        Date: "30/12/17",
        HomeTeam: "Torino",
        AwayTeam: "Genoa",
        HomeGoals: 0,
        AwayGoals: 0,
      },
      {
        Date: "30/12/17",
        HomeTeam: "Verona",
        AwayTeam: "Juventus",
        HomeGoals: 1,
        AwayGoals: 3,
      },
      {
        Date: "05/01/18",
        HomeTeam: "Chievo",
        AwayTeam: "Udinese",
        HomeGoals: 1,
        AwayGoals: 1,
      },
      {
        Date: "05/01/18",
        HomeTeam: "Fiorentina",
        AwayTeam: "Inter",
        HomeGoals: 1,
        AwayGoals: 1,
      },
      {
        Date: "06/01/18",
        HomeTeam: "Benevento",
        AwayTeam: "Sampdoria",
        HomeGoals: 3,
        AwayGoals: 2,
      },
      {
        Date: "06/01/18",
        HomeTeam: "Cagliari",
        AwayTeam: "Juventus",
        HomeGoals: 0,
        AwayGoals: 1,
      },
      {
        Date: "06/01/18",
        HomeTeam: "Genoa",
        AwayTeam: "Sassuolo",
        HomeGoals: 1,
        AwayGoals: 0,
      },
      {
        Date: "06/01/18",
        HomeTeam: "Milan",
        AwayTeam: "Crotone",
        HomeGoals: 1,
        AwayGoals: 0,
      },
      {
        Date: "06/01/18",
        HomeTeam: "Napoli",
        AwayTeam: "Verona",
        HomeGoals: 2,
        AwayGoals: 0,
      },
      {
        Date: "06/01/18",
        HomeTeam: "Roma",
        AwayTeam: "Atalanta",
        HomeGoals: 1,
        AwayGoals: 2,
      },
      {
        Date: "06/01/18",
        HomeTeam: "Spal",
        AwayTeam: "Lazio",
        HomeGoals: 2,
        AwayGoals: 5,
      },
      {
        Date: "06/01/18",
        HomeTeam: "Torino",
        AwayTeam: "Bologna",
        HomeGoals: 3,
        AwayGoals: 0,
      },
      {
        Date: "21/01/18",
        HomeTeam: "Atalanta",
        AwayTeam: "Napoli",
        HomeGoals: 0,
        AwayGoals: 1,
      },
      {
        Date: "21/01/18",
        HomeTeam: "Bologna",
        AwayTeam: "Benevento",
        HomeGoals: 3,
        AwayGoals: 0,
      },
      {
        Date: "21/01/18",
        HomeTeam: "Cagliari",
        AwayTeam: "Milan",
        HomeGoals: 1,
        AwayGoals: 2,
      },
      {
        Date: "21/01/18",
        HomeTeam: "Inter",
        AwayTeam: "Roma",
        HomeGoals: 1,
        AwayGoals: 1,
      },
      {
        Date: "21/01/18",
        HomeTeam: "Lazio",
        AwayTeam: "Chievo",
        HomeGoals: 5,
        AwayGoals: 1,
      },
      {
        Date: "21/01/18",
        HomeTeam: "Sampdoria",
        AwayTeam: "Fiorentina",
        HomeGoals: 3,
        AwayGoals: 1,
      },
      {
        Date: "21/01/18",
        HomeTeam: "Sassuolo",
        AwayTeam: "Torino",
        HomeGoals: 1,
        AwayGoals: 1,
      },
      {
        Date: "21/01/18",
        HomeTeam: "Udinese",
        AwayTeam: "Spal",
        HomeGoals: 1,
        AwayGoals: 1,
      },
      {
        Date: "21/01/18",
        HomeTeam: "Verona",
        AwayTeam: "Crotone",
        HomeGoals: 0,
        AwayGoals: 3,
      },
      {
        Date: "22/01/18",
        HomeTeam: "Juventus",
        AwayTeam: "Genoa",
        HomeGoals: 1,
        AwayGoals: 0,
      },
      {
        Date: "24/01/18",
        HomeTeam: "Lazio",
        AwayTeam: "Udinese",
        HomeGoals: 3,
        AwayGoals: 0,
      },
      {
        Date: "24/01/18",
        HomeTeam: "Sampdoria",
        AwayTeam: "Roma",
        HomeGoals: 1,
        AwayGoals: 1,
      },
      {
        Date: "27/01/18",
        HomeTeam: "Chievo",
        AwayTeam: "Juventus",
        HomeGoals: 0,
        AwayGoals: 2,
      },
      {
        Date: "27/01/18",
        HomeTeam: "Sassuolo",
        AwayTeam: "Atalanta",
        HomeGoals: 0,
        AwayGoals: 3,
      },
      {
        Date: "28/01/18",
        HomeTeam: "Crotone",
        AwayTeam: "Cagliari",
        HomeGoals: 1,
        AwayGoals: 1,
      },
      {
        Date: "28/01/18",
        HomeTeam: "Fiorentina",
        AwayTeam: "Verona",
        HomeGoals: 1,
        AwayGoals: 4,
      },
      {
        Date: "28/01/18",
        HomeTeam: "Genoa",
        AwayTeam: "Udinese",
        HomeGoals: 0,
        AwayGoals: 1,
      },
      {
        Date: "28/01/18",
        HomeTeam: "Milan",
        AwayTeam: "Lazio",
        HomeGoals: 2,
        AwayGoals: 1,
      },
      {
        Date: "28/01/18",
        HomeTeam: "Napoli",
        AwayTeam: "Bologna",
        HomeGoals: 3,
        AwayGoals: 1,
      },
      {
        Date: "28/01/18",
        HomeTeam: "Roma",
        AwayTeam: "Sampdoria",
        HomeGoals: 0,
        AwayGoals: 1,
      },
      {
        Date: "28/01/18",
        HomeTeam: "Spal",
        AwayTeam: "Inter",
        HomeGoals: 1,
        AwayGoals: 1,
      },
      {
        Date: "28/01/18",
        HomeTeam: "Torino",
        AwayTeam: "Benevento",
        HomeGoals: 3,
        AwayGoals: 0,
      },
      {
        Date: "03/02/18",
        HomeTeam: "Inter",
        AwayTeam: "Crotone",
        HomeGoals: 1,
        AwayGoals: 1,
      },
      {
        Date: "03/02/18",
        HomeTeam: "Sampdoria",
        AwayTeam: "Torino",
        HomeGoals: 1,
        AwayGoals: 1,
      },
      {
        Date: "04/02/18",
        HomeTeam: "Atalanta",
        AwayTeam: "Chievo",
        HomeGoals: 1,
        AwayGoals: 0,
      },
      {
        Date: "04/02/18",
        HomeTeam: "Benevento",
        AwayTeam: "Napoli",
        HomeGoals: 0,
        AwayGoals: 2,
      },
      {
        Date: "04/02/18",
        HomeTeam: "Bologna",
        AwayTeam: "Fiorentina",
        HomeGoals: 1,
        AwayGoals: 2,
      },
      {
        Date: "04/02/18",
        HomeTeam: "Cagliari",
        AwayTeam: "Spal",
        HomeGoals: 2,
        AwayGoals: 0,
      },
      {
        Date: "04/02/18",
        HomeTeam: "Juventus",
        AwayTeam: "Sassuolo",
        HomeGoals: 7,
        AwayGoals: 0,
      },
      {
        Date: "04/02/18",
        HomeTeam: "Udinese",
        AwayTeam: "Milan",
        HomeGoals: 1,
        AwayGoals: 1,
      },
      {
        Date: "04/02/18",
        HomeTeam: "Verona",
        AwayTeam: "Roma",
        HomeGoals: 0,
        AwayGoals: 1,
      },
      {
        Date: "05/02/18",
        HomeTeam: "Lazio",
        AwayTeam: "Genoa",
        HomeGoals: 1,
        AwayGoals: 2,
      },
      {
        Date: "09/02/18",
        HomeTeam: "Fiorentina",
        AwayTeam: "Juventus",
        HomeGoals: 0,
        AwayGoals: 2,
      },
      {
        Date: "10/02/18",
        HomeTeam: "Crotone",
        AwayTeam: "Atalanta",
        HomeGoals: 1,
        AwayGoals: 1,
      },
      {
        Date: "10/02/18",
        HomeTeam: "Napoli",
        AwayTeam: "Lazio",
        HomeGoals: 4,
        AwayGoals: 1,
      },
      {
        Date: "10/02/18",
        HomeTeam: "Spal",
        AwayTeam: "Milan",
        HomeGoals: 0,
        AwayGoals: 4,
      },
      {
        Date: "11/02/18",
        HomeTeam: "Chievo",
        AwayTeam: "Genoa",
        HomeGoals: 0,
        AwayGoals: 1,
      },
      {
        Date: "11/02/18",
        HomeTeam: "Inter",
        AwayTeam: "Bologna",
        HomeGoals: 2,
        AwayGoals: 1,
      },
      {
        Date: "11/02/18",
        HomeTeam: "Roma",
        AwayTeam: "Benevento",
        HomeGoals: 5,
        AwayGoals: 2,
      },
      {
        Date: "11/02/18",
        HomeTeam: "Sampdoria",
        AwayTeam: "Verona",
        HomeGoals: 2,
        AwayGoals: 0,
      },
      {
        Date: "11/02/18",
        HomeTeam: "Sassuolo",
        AwayTeam: "Cagliari",
        HomeGoals: 0,
        AwayGoals: 0,
      },
      {
        Date: "11/02/18",
        HomeTeam: "Torino",
        AwayTeam: "Udinese",
        HomeGoals: 2,
        AwayGoals: 0,
      },
      {
        Date: "17/02/18",
        HomeTeam: "Chievo",
        AwayTeam: "Cagliari",
        HomeGoals: 2,
        AwayGoals: 1,
      },
      {
        Date: "17/02/18",
        HomeTeam: "Genoa",
        AwayTeam: "Inter",
        HomeGoals: 2,
        AwayGoals: 0,
      },
      {
        Date: "17/02/18",
        HomeTeam: "Udinese",
        AwayTeam: "Roma",
        HomeGoals: 0,
        AwayGoals: 2,
      },
      {
        Date: "18/02/18",
        HomeTeam: "Atalanta",
        AwayTeam: "Fiorentina",
        HomeGoals: 1,
        AwayGoals: 1,
      },
      {
        Date: "18/02/18",
        HomeTeam: "Benevento",
        AwayTeam: "Crotone",
        HomeGoals: 3,
        AwayGoals: 2,
      },
      {
        Date: "18/02/18",
        HomeTeam: "Bologna",
        AwayTeam: "Sassuolo",
        HomeGoals: 2,
        AwayGoals: 1,
      },
      {
        Date: "18/02/18",
        HomeTeam: "Milan",
        AwayTeam: "Sampdoria",
        HomeGoals: 1,
        AwayGoals: 0,
      },
      {
        Date: "18/02/18",
        HomeTeam: "Napoli",
        AwayTeam: "Spal",
        HomeGoals: 1,
        AwayGoals: 0,
      },
      {
        Date: "18/02/18",
        HomeTeam: "Torino",
        AwayTeam: "Juventus",
        HomeGoals: 0,
        AwayGoals: 1,
      },
      {
        Date: "19/02/18",
        HomeTeam: "Lazio",
        AwayTeam: "Verona",
        HomeGoals: 2,
        AwayGoals: 0,
      },
      {
        Date: "24/02/18",
        HomeTeam: "Bologna",
        AwayTeam: "Genoa",
        HomeGoals: 2,
        AwayGoals: 0,
      },
      {
        Date: "24/02/18",
        HomeTeam: "Inter",
        AwayTeam: "Benevento",
        HomeGoals: 2,
        AwayGoals: 0,
      },
      {
        Date: "25/02/18",
        HomeTeam: "Crotone",
        AwayTeam: "Spal",
        HomeGoals: 2,
        AwayGoals: 3,
      },
      {
        Date: "25/02/18",
        HomeTeam: "Fiorentina",
        AwayTeam: "Chievo",
        HomeGoals: 1,
        AwayGoals: 0,
      },
      {
        Date: "25/02/18",
        HomeTeam: "Roma",
        AwayTeam: "Milan",
        HomeGoals: 0,
        AwayGoals: 2,
      },
      {
        Date: "25/02/18",
        HomeTeam: "Sampdoria",
        AwayTeam: "Udinese",
        HomeGoals: 2,
        AwayGoals: 1,
      },
      {
        Date: "25/02/18",
        HomeTeam: "Sassuolo",
        AwayTeam: "Lazio",
        HomeGoals: 0,
        AwayGoals: 3,
      },
      {
        Date: "25/02/18",
        HomeTeam: "Verona",
        AwayTeam: "Torino",
        HomeGoals: 2,
        AwayGoals: 1,
      },
      {
        Date: "26/02/18",
        HomeTeam: "Cagliari",
        AwayTeam: "Napoli",
        HomeGoals: 0,
        AwayGoals: 5,
      },
      {
        Date: "03/03/18",
        HomeTeam: "Lazio",
        AwayTeam: "Juventus",
        HomeGoals: 0,
        AwayGoals: 1,
      },
      {
        Date: "03/03/18",
        HomeTeam: "Napoli",
        AwayTeam: "Roma",
        HomeGoals: 2,
        AwayGoals: 4,
      },
      {
        Date: "03/03/18",
        HomeTeam: "Spal",
        AwayTeam: "Bologna",
        HomeGoals: 1,
        AwayGoals: 0,
      },
      {
        Date: "09/03/18",
        HomeTeam: "Roma",
        AwayTeam: "Torino",
        HomeGoals: 3,
        AwayGoals: 0,
      },
      {
        Date: "10/03/18",
        HomeTeam: "Verona",
        AwayTeam: "Chievo",
        HomeGoals: 1,
        AwayGoals: 0,
      },
      {
        Date: "11/03/18",
        HomeTeam: "Bologna",
        AwayTeam: "Atalanta",
        HomeGoals: 0,
        AwayGoals: 1,
      },
      {
        Date: "11/03/18",
        HomeTeam: "Cagliari",
        AwayTeam: "Lazio",
        HomeGoals: 2,
        AwayGoals: 2,
      },
      {
        Date: "11/03/18",
        HomeTeam: "Crotone",
        AwayTeam: "Sampdoria",
        HomeGoals: 4,
        AwayGoals: 1,
      },
      {
        Date: "11/03/18",
        HomeTeam: "Fiorentina",
        AwayTeam: "Benevento",
        HomeGoals: 1,
        AwayGoals: 0,
      },
      {
        Date: "11/03/18",
        HomeTeam: "Genoa",
        AwayTeam: "Milan",
        HomeGoals: 0,
        AwayGoals: 1,
      },
      {
        Date: "11/03/18",
        HomeTeam: "Inter",
        AwayTeam: "Napoli",
        HomeGoals: 0,
        AwayGoals: 0,
      },
      {
        Date: "11/03/18",
        HomeTeam: "Juventus",
        AwayTeam: "Udinese",
        HomeGoals: 2,
        AwayGoals: 0,
      },
      {
        Date: "11/03/18",
        HomeTeam: "Sassuolo",
        AwayTeam: "Spal",
        HomeGoals: 1,
        AwayGoals: 1,
      },
      {
        Date: "14/03/18",
        HomeTeam: "Juventus",
        AwayTeam: "Atalanta",
        HomeGoals: 2,
        AwayGoals: 0,
      },
      {
        Date: "17/03/18",
        HomeTeam: "Spal",
        AwayTeam: "Juventus",
        HomeGoals: 0,
        AwayGoals: 0,
      },
      {
        Date: "17/03/18",
        HomeTeam: "Udinese",
        AwayTeam: "Sassuolo",
        HomeGoals: 1,
        AwayGoals: 2,
      },
      {
        Date: "18/03/18",
        HomeTeam: "Benevento",
        AwayTeam: "Cagliari",
        HomeGoals: 1,
        AwayGoals: 2,
      },
      {
        Date: "18/03/18",
        HomeTeam: "Crotone",
        AwayTeam: "Roma",
        HomeGoals: 0,
        AwayGoals: 2,
      },
      {
        Date: "18/03/18",
        HomeTeam: "Lazio",
        AwayTeam: "Bologna",
        HomeGoals: 1,
        AwayGoals: 1,
      },
      {
        Date: "18/03/18",
        HomeTeam: "Milan",
        AwayTeam: "Chievo",
        HomeGoals: 3,
        AwayGoals: 2,
      },
      {
        Date: "18/03/18",
        HomeTeam: "Napoli",
        AwayTeam: "Genoa",
        HomeGoals: 1,
        AwayGoals: 0,
      },
      {
        Date: "18/03/18",
        HomeTeam: "Sampdoria",
        AwayTeam: "Inter",
        HomeGoals: 0,
        AwayGoals: 5,
      },
      {
        Date: "18/03/18",
        HomeTeam: "Torino",
        AwayTeam: "Fiorentina",
        HomeGoals: 1,
        AwayGoals: 2,
      },
      {
        Date: "18/03/18",
        HomeTeam: "Verona",
        AwayTeam: "Atalanta",
        HomeGoals: 0,
        AwayGoals: 5,
      },
      {
        Date: "31/03/18",
        HomeTeam: "Atalanta",
        AwayTeam: "Udinese",
        HomeGoals: 2,
        AwayGoals: 0,
      },
      {
        Date: "31/03/18",
        HomeTeam: "Bologna",
        AwayTeam: "Roma",
        HomeGoals: 1,
        AwayGoals: 1,
      },
      {
        Date: "31/03/18",
        HomeTeam: "Cagliari",
        AwayTeam: "Torino",
        HomeGoals: 0,
        AwayGoals: 4,
      },
      {
        Date: "31/03/18",
        HomeTeam: "Chievo",
        AwayTeam: "Sampdoria",
        HomeGoals: 2,
        AwayGoals: 1,
      },
      {
        Date: "31/03/18",
        HomeTeam: "Fiorentina",
        AwayTeam: "Crotone",
        HomeGoals: 2,
        AwayGoals: 0,
      },
      {
        Date: "31/03/18",
        HomeTeam: "Genoa",
        AwayTeam: "Spal",
        HomeGoals: 1,
        AwayGoals: 1,
      },
      {
        Date: "31/03/18",
        HomeTeam: "Inter",
        AwayTeam: "Verona",
        HomeGoals: 3,
        AwayGoals: 0,
      },
      {
        Date: "31/03/18",
        HomeTeam: "Juventus",
        AwayTeam: "Milan",
        HomeGoals: 3,
        AwayGoals: 1,
      },
      {
        Date: "31/03/18",
        HomeTeam: "Lazio",
        AwayTeam: "Benevento",
        HomeGoals: 6,
        AwayGoals: 2,
      },
      {
        Date: "31/03/18",
        HomeTeam: "Sassuolo",
        AwayTeam: "Napoli",
        HomeGoals: 1,
        AwayGoals: 1,
      },
      {
        Date: "03/04/18",
        HomeTeam: "Atalanta",
        AwayTeam: "Sampdoria",
        HomeGoals: 1,
        AwayGoals: 2,
      },
      {
        Date: "03/04/18",
        HomeTeam: "Genoa",
        AwayTeam: "Cagliari",
        HomeGoals: 2,
        AwayGoals: 1,
      },
      {
        Date: "03/04/18",
        HomeTeam: "Udinese",
        AwayTeam: "Fiorentina",
        HomeGoals: 0,
        AwayGoals: 2,
      },
      {
        Date: "04/04/18",
        HomeTeam: "Benevento",
        AwayTeam: "Verona",
        HomeGoals: 3,
        AwayGoals: 0,
      },
      {
        Date: "04/04/18",
        HomeTeam: "Chievo",
        AwayTeam: "Sassuolo",
        HomeGoals: 1,
        AwayGoals: 1,
      },
      {
        Date: "04/04/18",
        HomeTeam: "Milan",
        AwayTeam: "Inter",
        HomeGoals: 0,
        AwayGoals: 0,
      },
      {
        Date: "04/04/18",
        HomeTeam: "Torino",
        AwayTeam: "Crotone",
        HomeGoals: 4,
        AwayGoals: 1,
      },
      {
        Date: "07/04/18",
        HomeTeam: "Benevento",
        AwayTeam: "Juventus",
        HomeGoals: 2,
        AwayGoals: 4,
      },
      {
        Date: "07/04/18",
        HomeTeam: "Roma",
        AwayTeam: "Fiorentina",
        HomeGoals: 0,
        AwayGoals: 2,
      },
      {
        Date: "07/04/18",
        HomeTeam: "Sampdoria",
        AwayTeam: "Genoa",
        HomeGoals: 0,
        AwayGoals: 0,
      },
      {
        Date: "07/04/18",
        HomeTeam: "Spal",
        AwayTeam: "Atalanta",
        HomeGoals: 1,
        AwayGoals: 1,
      },
      {
        Date: "08/04/18",
        HomeTeam: "Crotone",
        AwayTeam: "Bologna",
        HomeGoals: 1,
        AwayGoals: 0,
      },
      {
        Date: "08/04/18",
        HomeTeam: "Milan",
        AwayTeam: "Sassuolo",
        HomeGoals: 1,
        AwayGoals: 1,
      },
      {
        Date: "08/04/18",
        HomeTeam: "Napoli",
        AwayTeam: "Chievo",
        HomeGoals: 2,
        AwayGoals: 1,
      },
      {
        Date: "08/04/18",
        HomeTeam: "Torino",
        AwayTeam: "Inter",
        HomeGoals: 1,
        AwayGoals: 0,
      },
      {
        Date: "08/04/18",
        HomeTeam: "Udinese",
        AwayTeam: "Lazio",
        HomeGoals: 1,
        AwayGoals: 2,
      },
      {
        Date: "08/04/18",
        HomeTeam: "Verona",
        AwayTeam: "Cagliari",
        HomeGoals: 1,
        AwayGoals: 0,
      },
      {
        Date: "14/04/18",
        HomeTeam: "Atalanta",
        AwayTeam: "Inter",
        HomeGoals: 0,
        AwayGoals: 0,
      },
      {
        Date: "14/04/18",
        HomeTeam: "Cagliari",
        AwayTeam: "Udinese",
        HomeGoals: 2,
        AwayGoals: 1,
      },
      {
        Date: "14/04/18",
        HomeTeam: "Chievo",
        AwayTeam: "Torino",
        HomeGoals: 0,
        AwayGoals: 0,
      },
      {
        Date: "14/04/18",
        HomeTeam: "Genoa",
        AwayTeam: "Crotone",
        HomeGoals: 1,
        AwayGoals: 0,
      },
      {
        Date: "15/04/18",
        HomeTeam: "Bologna",
        AwayTeam: "Verona",
        HomeGoals: 2,
        AwayGoals: 0,
      },
      {
        Date: "15/04/18",
        HomeTeam: "Fiorentina",
        AwayTeam: "Spal",
        HomeGoals: 0,
        AwayGoals: 0,
      },
      {
        Date: "15/04/18",
        HomeTeam: "Juventus",
        AwayTeam: "Sampdoria",
        HomeGoals: 3,
        AwayGoals: 0,
      },
      {
        Date: "15/04/18",
        HomeTeam: "Lazio",
        AwayTeam: "Roma",
        HomeGoals: 0,
        AwayGoals: 0,
      },
      {
        Date: "15/04/18",
        HomeTeam: "Milan",
        AwayTeam: "Napoli",
        HomeGoals: 0,
        AwayGoals: 0,
      },
      {
        Date: "15/04/18",
        HomeTeam: "Sassuolo",
        AwayTeam: "Benevento",
        HomeGoals: 2,
        AwayGoals: 2,
      },
      {
        Date: "17/04/18",
        HomeTeam: "Inter",
        AwayTeam: "Cagliari",
        HomeGoals: 4,
        AwayGoals: 0,
      },
      {
        Date: "18/04/18",
        HomeTeam: "Benevento",
        AwayTeam: "Atalanta",
        HomeGoals: 0,
        AwayGoals: 3,
      },
      {
        Date: "18/04/18",
        HomeTeam: "Crotone",
        AwayTeam: "Juventus",
        HomeGoals: 1,
        AwayGoals: 1,
      },
      {
        Date: "18/04/18",
        HomeTeam: "Fiorentina",
        AwayTeam: "Lazio",
        HomeGoals: 3,
        AwayGoals: 4,
      },
      {
        Date: "18/04/18",
        HomeTeam: "Napoli",
        AwayTeam: "Udinese",
        HomeGoals: 4,
        AwayGoals: 2,
      },
      {
        Date: "18/04/18",
        HomeTeam: "Roma",
        AwayTeam: "Genoa",
        HomeGoals: 2,
        AwayGoals: 1,
      },
      {
        Date: "18/04/18",
        HomeTeam: "Sampdoria",
        AwayTeam: "Bologna",
        HomeGoals: 1,
        AwayGoals: 0,
      },
      {
        Date: "18/04/18",
        HomeTeam: "Spal",
        AwayTeam: "Chievo",
        HomeGoals: 0,
        AwayGoals: 0,
      },
      {
        Date: "18/04/18",
        HomeTeam: "Torino",
        AwayTeam: "Milan",
        HomeGoals: 1,
        AwayGoals: 1,
      },
      {
        Date: "18/04/18",
        HomeTeam: "Verona",
        AwayTeam: "Sassuolo",
        HomeGoals: 0,
        AwayGoals: 1,
      },
      {
        Date: "21/04/18",
        HomeTeam: "Milan",
        AwayTeam: "Benevento",
        HomeGoals: 0,
        AwayGoals: 1,
      },
      {
        Date: "21/04/18",
        HomeTeam: "Sassuolo",
        AwayTeam: "Fiorentina",
        HomeGoals: 1,
        AwayGoals: 0,
      },
      {
        Date: "21/04/18",
        HomeTeam: "Spal",
        AwayTeam: "Roma",
        HomeGoals: 0,
        AwayGoals: 3,
      },
      {
        Date: "22/04/18",
        HomeTeam: "Atalanta",
        AwayTeam: "Torino",
        HomeGoals: 2,
        AwayGoals: 1,
      },
      {
        Date: "22/04/18",
        HomeTeam: "Cagliari",
        AwayTeam: "Bologna",
        HomeGoals: 0,
        AwayGoals: 0,
      },
      {
        Date: "22/04/18",
        HomeTeam: "Chievo",
        AwayTeam: "Inter",
        HomeGoals: 1,
        AwayGoals: 2,
      },
      {
        Date: "22/04/18",
        HomeTeam: "Juventus",
        AwayTeam: "Napoli",
        HomeGoals: 0,
        AwayGoals: 1,
      },
      {
        Date: "22/04/18",
        HomeTeam: "Lazio",
        AwayTeam: "Sampdoria",
        HomeGoals: 4,
        AwayGoals: 0,
      },
      {
        Date: "22/04/18",
        HomeTeam: "Udinese",
        AwayTeam: "Crotone",
        HomeGoals: 1,
        AwayGoals: 2,
      },
      {
        Date: "23/04/18",
        HomeTeam: "Genoa",
        AwayTeam: "Verona",
        HomeGoals: 3,
        AwayGoals: 1,
      },
      {
        Date: "28/04/18",
        HomeTeam: "Inter",
        AwayTeam: "Juventus",
        HomeGoals: 2,
        AwayGoals: 3,
      },
      {
        Date: "28/04/18",
        HomeTeam: "Roma",
        AwayTeam: "Chievo",
        HomeGoals: 4,
        AwayGoals: 1,
      },
      {
        Date: "29/04/18",
        HomeTeam: "Atalanta",
        AwayTeam: "Genoa",
        HomeGoals: 3,
        AwayGoals: 1,
      },
      {
        Date: "29/04/18",
        HomeTeam: "Benevento",
        AwayTeam: "Udinese",
        HomeGoals: 3,
        AwayGoals: 3,
      },
      {
        Date: "29/04/18",
        HomeTeam: "Bologna",
        AwayTeam: "Milan",
        HomeGoals: 1,
        AwayGoals: 2,
      },
      {
        Date: "29/04/18",
        HomeTeam: "Crotone",
        AwayTeam: "Sassuolo",
        HomeGoals: 4,
        AwayGoals: 1,
      },
      {
        Date: "29/04/18",
        HomeTeam: "Fiorentina",
        AwayTeam: "Napoli",
        HomeGoals: 3,
        AwayGoals: 0,
      },
      {
        Date: "29/04/18",
        HomeTeam: "Sampdoria",
        AwayTeam: "Cagliari",
        HomeGoals: 4,
        AwayGoals: 1,
      },
      {
        Date: "29/04/18",
        HomeTeam: "Torino",
        AwayTeam: "Lazio",
        HomeGoals: 0,
        AwayGoals: 1,
      },
      {
        Date: "29/04/18",
        HomeTeam: "Verona",
        AwayTeam: "Spal",
        HomeGoals: 1,
        AwayGoals: 3,
      },
      {
        Date: "05/05/18",
        HomeTeam: "Juventus",
        AwayTeam: "Bologna",
        HomeGoals: 3,
        AwayGoals: 1,
      },
      {
        Date: "05/05/18",
        HomeTeam: "Milan",
        AwayTeam: "Verona",
        HomeGoals: 4,
        AwayGoals: 1,
      },
      {
        Date: "06/05/18",
        HomeTeam: "Cagliari",
        AwayTeam: "Roma",
        HomeGoals: 0,
        AwayGoals: 1,
      },
      {
        Date: "06/05/18",
        HomeTeam: "Chievo",
        AwayTeam: "Crotone",
        HomeGoals: 2,
        AwayGoals: 1,
      },
      {
        Date: "06/05/18",
        HomeTeam: "Genoa",
        AwayTeam: "Fiorentina",
        HomeGoals: 2,
        AwayGoals: 3,
      },
      {
        Date: "06/05/18",
        HomeTeam: "Lazio",
        AwayTeam: "Atalanta",
        HomeGoals: 1,
        AwayGoals: 1,
      },
      {
        Date: "06/05/18",
        HomeTeam: "Napoli",
        AwayTeam: "Torino",
        HomeGoals: 2,
        AwayGoals: 2,
      },
      {
        Date: "06/05/18",
        HomeTeam: "Sassuolo",
        AwayTeam: "Sampdoria",
        HomeGoals: 1,
        AwayGoals: 0,
      },
      {
        Date: "06/05/18",
        HomeTeam: "Spal",
        AwayTeam: "Benevento",
        HomeGoals: 2,
        AwayGoals: 0,
      },
      {
        Date: "06/05/18",
        HomeTeam: "Udinese",
        AwayTeam: "Inter",
        HomeGoals: 0,
        AwayGoals: 4,
      },
      {
        Date: "12/05/18",
        HomeTeam: "Benevento",
        AwayTeam: "Genoa",
        HomeGoals: 1,
        AwayGoals: 0,
      },
      {
        Date: "12/05/18",
        HomeTeam: "Inter",
        AwayTeam: "Sassuolo",
        HomeGoals: 1,
        AwayGoals: 2,
      },
      {
        Date: "13/05/18",
        HomeTeam: "Atalanta",
        AwayTeam: "Milan",
        HomeGoals: 1,
        AwayGoals: 1,
      },
      {
        Date: "13/05/18",
        HomeTeam: "Bologna",
        AwayTeam: "Chievo",
        HomeGoals: 1,
        AwayGoals: 2,
      },
      {
        Date: "13/05/18",
        HomeTeam: "Crotone",
        AwayTeam: "Lazio",
        HomeGoals: 2,
        AwayGoals: 2,
      },
      {
        Date: "13/05/18",
        HomeTeam: "Fiorentina",
        AwayTeam: "Cagliari",
        HomeGoals: 0,
        AwayGoals: 1,
      },
      {
        Date: "13/05/18",
        HomeTeam: "Roma",
        AwayTeam: "Juventus",
        HomeGoals: 0,
        AwayGoals: 0,
      },
      {
        Date: "13/05/18",
        HomeTeam: "Sampdoria",
        AwayTeam: "Napoli",
        HomeGoals: 0,
        AwayGoals: 2,
      },
      {
        Date: "13/05/18",
        HomeTeam: "Torino",
        AwayTeam: "Spal",
        HomeGoals: 2,
        AwayGoals: 1,
      },
      {
        Date: "13/05/18",
        HomeTeam: "Verona",
        AwayTeam: "Udinese",
        HomeGoals: 0,
        AwayGoals: 1,
      },
      {
        Date: "19/05/18",
        HomeTeam: "Juventus",
        AwayTeam: "Verona",
        HomeGoals: 2,
        AwayGoals: 1,
      },
      {
        Date: "20/05/18",
        HomeTeam: "Cagliari",
        AwayTeam: "Atalanta",
        HomeGoals: 1,
        AwayGoals: 0,
      },
      {
        Date: "20/05/18",
        HomeTeam: "Chievo",
        AwayTeam: "Benevento",
        HomeGoals: 1,
        AwayGoals: 0,
      },
      {
        Date: "20/05/18",
        HomeTeam: "Genoa",
        AwayTeam: "Torino",
        HomeGoals: 1,
        AwayGoals: 2,
      },
      {
        Date: "20/05/18",
        HomeTeam: "Lazio",
        AwayTeam: "Inter",
        HomeGoals: 2,
        AwayGoals: 3,
      },
      {
        Date: "20/05/18",
        HomeTeam: "Milan",
        AwayTeam: "Fiorentina",
        HomeGoals: 5,
        AwayGoals: 1,
      },
      {
        Date: "20/05/18",
        HomeTeam: "Napoli",
        AwayTeam: "Crotone",
        HomeGoals: 2,
        AwayGoals: 1,
      },
      {
        Date: "20/05/18",
        HomeTeam: "Sassuolo",
        AwayTeam: "Roma",
        HomeGoals: 0,
        AwayGoals: 1,
      },
      {
        Date: "20/05/18",
        HomeTeam: "Spal",
        AwayTeam: "Sampdoria",
        HomeGoals: 3,
        AwayGoals: 1,
      },
      {
        Date: "20/05/18",
        HomeTeam: "Udinese",
        AwayTeam: "Bologna",
        HomeGoals: 1,
        AwayGoals: 0,
      },
    ];

  //=======================================To convert lowercase search term first letter to capital===========================//
    let newSearch = search.split('');
    newSearch[0] = newSearch[0].toUpperCase();
     search = newSearch.join(""); 

    let allPlayed = data.filter((x) => Object.values(x).includes(search));
    if (!allPlayed) {
      alert("This team does not exist. Try again");
    } else {
      let numberPlayed = allPlayed.length;

      //=============homegames==========================================//
      let homeGames = allPlayed.filter((x) => x.HomeTeam === search);
      let numberHomePlayed = homeGames.length;
      let homeWins = homeGames.filter((x) => x.HomeGoals > x.AwayGoals);
      let numberHomeWins = homeWins.length;
      let homeWinTeams = homeWins.map((x) => x.AwayTeam);

      //===============awaygames========================================//
      let awayGames = allPlayed.filter((x) => x.AwayTeam === search);
      let numberAwayPlayed = awayGames.length;
      let awayWins = awayGames.filter((x) => x.AwayGoals > x.HomeGoals);
      let numberAwayWins = awayWins.length;
      let awayWinTeams = awayWins.map((x) => x.HomeTeam);

      let allWins = [...homeWinTeams, ...awayWinTeams];
      let numberWins = allWins.length;

      return allWins;
    }
  }

  render() {
    return (
      <div className="sportsPanel">
        <div className="sports-title">Sports</div>
        <form onSubmit={this.handleSubmit}>
          <input
            type="text"
            className="search-input"
            placeholder="search for an Italian team"
            value={this.state.value}
            onChange={this.handleChange}
          />
          <button type="input" value="Submit" onClick={this.handleSubmit}>
            Submit
          </button>
        </form>
        <div className="wins-list">
          {this.state.value} defeated:
          {this.state.wins.map((x) => (
            <button className="teams" key={x}>{x}</button>
          ))}
        </div>
      </div>
    );
  }
}

export default Sports;
